require("plugins-config.tokyonight")
require("plugins-config.poimandres")
require("plugins-config.dashboard")
require("plugins-config.lualine")
require("plugins-config.telescope")
require("plugins-config.neotree")
require("plugins-config.bufferline")
require("plugins-config.notify")
require("plugins-config.lsp")
require("plugins-config.treesitter")
require("plugins-config.pickColor")
require("plugins-config.wilder")
-- require("plugins-config.indentBlankline")
require("plugins-config.toggleterm")
require("plugins-config.comment")
require("plugins-config.diffview")
require("plugins-config.cursorline")
