require ("plugins-config/tokyonight")
--require ("plugins-config/nightfox")
require ("plugins-config/lualine")
require ("plugins-config/dashboard")
require ("plugins-config/telescope")
require ("plugins-config/tabby")
require ("plugins-config/nvim-tree")
